[package]
name = "git-cache-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
camino = "1.1.9"
either = "1.15.0"
shellexpand = "3.1.1"
signal-hook = { version = "0.3.18", default-features = false }
smol = "2.0.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
